spring:
  r2dbc:        
    url: ${SPRING_R2DBC_URL:r2dbc:postgresql://localhost:5432/postgres}
    username: ${SPRING_R2DBC_USERNAME:postgres}
    password: ${SPRING_R2DBC_PASSWORD:postgres}
app:
  status:
    pendiente: 1
    aprobado: 2
    rechazado: 3
    atendido: 4
    recojo: 5
    proceso: 6
    custom: 7
  type:
    vouchercertificado: 1
    vouchercontrato: 2
    voucherrectificacion: 50
    solicitudcertificado: 101
    solicitudcontrato: 102
  

