spring:
  r2dbc:
    username: sa
    password: 3FgvGJUTKnaKwnskFWNP2RXvw76jkgAc
    url: r2dbc:postgresql://sa:3FgvGJUTKnaKwnskFWNP2RXvw76jkgAc@dpg-d05poieuk2gs73cnedsg-a.oregon-postgres.render.com:5432/legal_fst8
    username2: postgres
    password2: postgres
    url2: r2dbc:postgresql://localhost:5432/postgres
app:
  status:
    pendiente: 1
    aprobado: 2
    rechazado: 3
    atendido: 4
    recojo: 5
    proceso: 6
    custom: 7
  type:
    vouchercertificado: 1
    vouchercontrato: 2
    voucherrectificacion: 50
    solicitudcertificado: 101
    solicitudcontrato: 102
  

