spring:
  application.name: bo-legal-microservice
  config.import: optional:configserver:${CONFIG_SERVER_URL:http://bosrvcfg.inclub.world/}

app:
  status:
    pendiente: 1
    aprobado: 2
    rechazado: 3
    atendido: 4
    recojo: 5
    proceso: 6
    custom: 7
  type:
    vouchercertificado: 1
    vouchercontrato: 2
    voucherrectificacion: 50
    solicitudcertificado: 101
    solicitudcontrato: 102
  

