spring:
  profiles:
    active: prod # dev o prod (esto puedes sobreescribir en línea de comandos o variables de entorno)
server:
  port: ${PORT:8080}
app:
  status:
    pendiente: 1
    aprobado: 2
    rechazado: 3
    atendido: 4
    recojo: 5
    proceso: 6
    custom: 7
  type:
    vouchercertificado: 1
    vouchercontrato: 2
    voucherrectificacion: 50
    solicitudcertificado: 101
    solicitudcontrato: 102

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    prometheus:
      access: UNRESTRICTED
  prometheus:
    metrics:
      export:
        enabled: true